import os
from dotenv import load_dotenv

os.environ["ANONYMIZED_TELEMETRY"] = "False"

load_dotenv()

class Settings:
    DB_DRIVER = os.getenv("DB_DRIVER")
    DB_SERVER = os.getenv("DB_SERVER")
    DB_DATABASE = os.getenv("DB_DATABASE")
    DB_USER = os.getenv("DB_USER")
    DB_PASSWORD = os.getenv("DB_PASSWORD")
    DB_TRUST_CERT = os.getenv("DB_TRUST_CERT", "yes")

    FAMILY_SALE_DB_DRIVER = os.getenv("FAMILY_SALE_DB_DRIVER", DB_DRIVER)
    FAMILY_SALE_DB_HOST = os.getenv("FAMILY_SALE_DB_HOST", "10.28.200.5")
    FAMILY_SALE_DB_PORT = int(os.getenv("FAMILY_SALE_DB_PORT", "1433"))
    FAMILY_SALE_DB_DATABASE = os.getenv("FAMILY_SALE_DB_DATABASE", "HDTRAN")
    FAMILY_SALE_DB_USER = os.getenv("FAMILY_SALE_DB_USER")
    FAMILY_SALE_DB_PASSWORD = os.getenv("FAMILY_SALE_DB_PASSWORD")
    FAMILY_SALE_DB_TRUST_CERT = os.getenv("FAMILY_SALE_DB_TRUST_CERT", "yes")
    FAMILY_SALE_STORE_CD = os.getenv("FAMILY_SALE_STORE_CD", "480")
    FAMILY_SALE_CURRENT_POS_START = os.getenv("FAMILY_SALE_CURRENT_POS_START", "7701")
    FAMILY_SALE_CURRENT_POS_END = os.getenv("FAMILY_SALE_CURRENT_POS_END", "7793")
    FAMILY_SALE_PREVIOUS_POS_START = os.getenv("FAMILY_SALE_PREVIOUS_POS_START", "7701")
    FAMILY_SALE_PREVIOUS_POS_END = os.getenv("FAMILY_SALE_PREVIOUS_POS_END", "7783")
    FAMILY_SALE_CURRENT_EVENT_START_DATE = os.getenv(
        "FAMILY_SALE_CURRENT_EVENT_START_DATE", "2026-08-13"
    )
    FAMILY_SALE_PREVIOUS_EVENT_START_DATE = os.getenv(
        "FAMILY_SALE_PREVIOUS_EVENT_START_DATE", "2025-08-14"
    )
    FAMILY_SALE_QUERY_TIMEOUT_SEC = int(
        os.getenv("FAMILY_SALE_QUERY_TIMEOUT_SEC", "30")
    )

    CHROMA_DIR = os.getenv("CHROMA_DIR", "./data/chroma")
    CHROMA_COLLECTION = os.getenv("CHROMA_COLLECTION", "pos_faq")
    CHROMA_TOMBSTONE_DB = os.getenv("CHROMA_TOMBSTONE_DB")
    IMAGE_RAG_MAX_DISTANCE = float(os.getenv("IMAGE_RAG_MAX_DISTANCE", "0.65"))
    IMAGE_RAG_FALLBACK_MAX_DISTANCE = float(
        os.getenv("IMAGE_RAG_FALLBACK_MAX_DISTANCE", "0.75")
    )
    IMAGE_RAG_MIN_DISTANCE_GAP = float(
        os.getenv("IMAGE_RAG_MIN_DISTANCE_GAP", "0.15")
    )
    IMAGE_RAG_CANDIDATE_COUNT = int(os.getenv("IMAGE_RAG_CANDIDATE_COUNT", "12"))

    AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
    AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
    AZURE_OPENAI_CHAT_DEPLOYMENT = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT")
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT")
    AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")

    MCP_BASE_URL = os.getenv("MCP_BASE_URL")
    MCP_API_KEY = os.getenv("MCP_API_KEY")
    MCP_TIMEOUT_SEC = int(os.getenv("MCP_TIMEOUT_SEC", "10"))

settings = Settings()
